### ISSUE TITLE
Performance Issue after upgrade from 3.0.18 to 3.1.4

### ISSUE THREAD

**Issue by satyamyesj** [ioc-fang/ioc-fanger#38]
@fhightower My team is observing a drastic performance decrease after upgrade from 3.0.18 to 3.1.4 following are the results for fanging same  506991 length string containing 282 IPv4 and 488 Domains.
3.0.18 -> Time taken 0.009386682510375976 Minutes 
3.1.14 -> Time taken 16.037531809012094 Minutes

I have done regex vs pyparsing performance analysis for same string where **regex substitution (0.5 seconds)** outperforms **pyparsing substitution (25 seconds)**. I used following definitions for comparison. 

```
def fang1(text):
         import time
         from pyparsing import Combine, Optional, White, Or, CaselessLiteral, replaceWith
         dot_parser = Combine(Optional(White(ws=" \t")) + Or([CaselessLiteral("(.)"), CaselessLiteral("(."), CaselessLiteral(".)")]) + Optional(White(ws=" \t")))
         dot_parser_with_repalce=dot_parser.addParseAction(replaceWith("."))
         start = time.time()
         text = dot_parser_with_repalce.transformString(text)
         print(f"Result: {text}")
         end=time.time()
         print(f"Time Taken {(end-start)} seconds")
```

```
def fang2(text):
         import time
         dot_pattern = re.compile("\(\.\)|\(\.|\.\)")
         space_pattern = re.compile("[ \t]*")
         start = time.time()
         text = re.sub(space_pattern, "", text)
         text = re.sub(dot_pattern, ".", text)
         print(f"Result: {text}")
         end= time.time()
         print(f"Time Taken {(end-start)} seconds")
```

**Comment by fhightower** [comment]
Thanks for mentioning this @satyamyesj! This looks like a serious problem - I'll take a look and get back to you with a solution.

**Comment by fhightower** [comment]
I'm working on this issue and hope to have a new version released early next week (shooting for Tuesday, March 9). I'm focusing on two things:

1. Improving the speed of this library (I think this will mean reverting to regexes)
2. Adding [benchmarks](https://github.com/ionelmc/pytest-benchmark) to some tests that will alert me if an update makes this library significantly slower

**Comment by fhightower** [comment]
@satyamyesj : Thanks again for reporting this issue! I've released a new version `v3.2.0` that runs much more quickly (and includes benchmarks in the tests to ensure there are no performance regressions in the future).

Please let me know if you have any further questions or concerns. Thanks!

**Comment by satyamyesj** [comment]
Thanks @fhightower for quick response and solution.

**Comment by fhightower** [comment]
Absolutely 😄 ! Thanks for reporting the issue and glad I could help.
