### ISSUE TITLE
Fix overzealous handling of spaces around square brackets ("[]")

### ISSUE THREAD

**Issue by fhightower** [ioc-fang/ioc-fanger#47]
This is a derivate of #46.

Given:

```python
ioc_fanger.fang('applications. [To')
```

We expect:

```
'applications. [To'
```

We get:

```
'applications.To'
```

**Comment by git-yogeshkumar** [comment]
@fhightower Just a question, have you considered giving support of angle brackets ('<>') for fanging IOCs. Cause my team has observed that there are scenarios where we get an IOC like 1<.>1<.>1<.>1.  Of Course we can have this fanging to be strict (basically to avoid any html reformatting, just a though). I would love to hear your thoughts on this!

**Comment by fhightower** [comment]
Great idea @git-yogeshkumar, we can do that! We'll make the regex strict enough that it won't reformat any html. I'm tracking this idea in #52 .
