### ISSUE TITLE
Improve fanging of "http" surrounded by angle brackets (">")

### ISSUE THREAD

**Issue by fhightower** [ioc-fang/ioc-fanger#48]
This is a derivate of #46.

Given:

```python
ioc_fanger.fang('<div>hxxp://example[.]com</div>')
```

We expect:

```
'<div>http://example.com</div>'
```

Current:

```
'<divhttps://example.com</div>'
```

**Comment by git-yogeshkumar** [comment]
Hi @fhightower, thanks for the prompt response, really glad that you are helping with this. I checked and the regex that is actually causing this error is r"(\b)\S{5}:\/\/" . The word break (\b) that we expect is not happening in the right place that is why it is not specific to angle ('<") brackets specifically. It just takes any non whitespace character (\S) 5 Times. Hope this helps!!

**Comment by git-yogeshkumar** [comment]
@fhightower Thanks for the quick response and resolution.

**Comment by fhightower** [comment]
You're welcome. Let me know if you run into any other issues or have any other suggestions.
