### ISSUE TITLE
Improve cli functions

### ISSUE THREAD

**Issue by fhightower** [ioc-fang/ioc-fanger#91]
In the cli functions ([here](https://github.com/ioc-fang/ioc-fanger/blob/06a22b5912375f74f624ae964049195c0d12c979/ioc_fanger/ioc_fanger.py#L94) is the one for the defanging operation), we have two ways to read input:

1. We can read from a given `text` argument
2. We can read from data which is 'piped' into the cli function via stdin text stream (e.g. `cat foo.txt | fang`)

We should move [this line](https://github.com/ioc-fang/ioc-fanger/blob/06a22b5912375f74f624ae964049195c0d12c979/ioc_fanger/ioc_fanger.py#L96) so that it is only run when necessary (if the user hasn't provided a `text` argument).

Please update both the [cli_defang](https://github.com/ioc-fang/ioc-fanger/blob/06a22b5912375f74f624ae964049195c0d12c979/ioc_fanger/ioc_fanger.py#L94) and [cli_fang](https://github.com/ioc-fang/ioc-fanger/blob/06a22b5912375f74f624ae964049195c0d12c979/ioc_fanger/ioc_fanger.py#L61) functions with this improvement.

**Comment by dhruvdabhi101** [comment]
I would like to give this issue a try. May I go for it ?

**Comment by fhightower** [comment]
Sure, thank you @dhruvdabhi101! Let me know if you have any questions.

**Comment by fhightower** [comment]
There is some documentation on local development [here](https://github.com/ioc-fang/ioc-fanger/blob/main/docs/local-dev.md) which may be helpful for testing your changes.

**Comment by dhruvdabhi101** [comment]
```python
@click.command()
@click.argument("text", required=False)
def cli_defang(text):
    """CLI interface for defanging indicators."""
    

    if text:
        defanged_text = defang(text)
        print(defanged_text)
        return
    stdin_text = click.get_text_stream("stdin")
    if stdin_text:
        for line in stdin_text:
            defanged_text = defang(line.rstrip("\n"))
            print(defanged_text)
```

Does this look okay?

**Comment by fhightower** [comment]
Yes, that looks good @dhruvdabhi101. Thanks!

**Comment by dhruvdabhi101** [comment]
> Yes, that looks good @dhruvdabhi101.

So Should I Create PR now ?

**Comment by fhightower** [comment]
Sorry for the late reply, but yes - a PR is perfect. (And I see you already created one - thanks!)

**Comment by fhightower** [comment]
Done with #95
